### PR TITLE
Added Properties.GetColor method.

### PR DESCRIPTION
**Pull request by tmathews**

### CODE REVIEW

**Comment by tmathews** [comment]
I can fix this and rebase it.

**Comment by tmathews** [comment]
This is good to go.

**Comment by lafriks** [comment]
From TMX format document:

> Color properties are stored in the format `#AARRGGBB`.

Maybe we should support both?

**Comment by tmathews** [comment]
Not sure I understand, this supports decoding `#AARRGGBB`. What do you mean by "both"?

**Comment by lafriks** [comment]
Damn, sorry, I did not read the code right must have been tired 😅

**Review by lafriks — APPROVED** [review]

**Comment by tmathews** [comment]
No worries, thanks!

**Pull request merged**
