### PR TITLE
Immediately load external tileset files

### PR DESCRIPTION
**Pull request by gpayer**
I had a problem with external tilesets not being loaded, when I wanted to access them, so I changed to loading logic to loading them immediately.

### CODE REVIEW

**Comment by lafriks** [comment]
Could you add unit test for your use case?

**Comment by lafriks** [comment]
Also please resolve conflicts

**Comment by gpayer** [comment]
Apparently something in the code either on my side or in go-tiled changed, so my original problem disappeared.
I'm closing the pull request.

**Comment by lafriks** [comment]
I probably accidentally fixed that while adding support for relative paths in tilesets in commit 1fb4256a00396552c25ccc51edb237361fd6e229

**Pull request closed without merging**
